server:
  port: 8094
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://176.201.111.5:3306/gteam?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.gt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.mapper: debug

    
#SpringBoot整合dubbo   
dubbo:
  scan:
    basePackages: com.gt    #扫描dubbo的注解
  application:
    name: provider-cart     #定义服务名称
  registry:                 #dubbo链接zookeeper
    address: zookeeper://176.201.111.21:2181?backup=176.201.111.21:2182,176.201.111.21:2183
  protocol:                 #协议
    name: dubbo             #dubbo协议
    port: 20881             #具体服务端口号 不能重复
    
    
    
    
    
    
    
