server:
  port: 8090
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

spring:     #定义springmvc视图解析器
  thymeleaf:
    prefix: classpath:/templates/views/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false


dubbo:
  scan:
    basePackages: com.gt    #包扫描路径
  application:
    name: consumer-web     #服务名称 可以调用其他服务
  registry:
    address: zookeeper://176.201.111.21:2181?backup=176.201.111.21:2182,176.201.111.21:2183


  